# Generated by Django 4.0.2 on 2022-02-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zipcoe',
            new_name='zipcode',
        ),
    ]
